module React.Flux.Rn.Components where

import React.Flux (foreign_)

activityIndicatorIOS = foreign_ "ActivityIndicatorIOS"
datePickerIOS = foreign_ "DatePickerIOS"
drawerLayoutAndroid = foreign_ "DrawerLayoutAndroid"
image = foreign_ "Image"
listView = foreign_ "ListView"
listView_DataSource = foreign_ "ListView.DataSource"
mapView = foreign_ "MapView"
modal = foreign_ "Modal"
navigator = foreign_ "Navigator"
navigatorIOS = foreign_ "NavigatorIOS"
pickerIOS = foreign_ "PickerIOS"
picker = foreign_ "Picker"
progressBarAndroid = foreign_ "ProgressBarAndroid"
progressViewIOS = foreign_ "ProgressViewIOS"
pullToRefreshViewAndroid = foreign_ "PullToRefreshViewAndroid"
refreshControl = foreign_ "RefreshControl"
scrollView = foreign_ "ScrollView"
segmentedControlIOS = foreign_ "SegmentedControlIOS"
sliderIOS = foreign_ "SliderIOS"
statusBar = foreign_ "StatusBar"
switch = foreign_ "Switch"
tabBarIOS = foreign_ "TabBarIOS"
tabBarIOS_Item = foreign_ "TabBarIOS.Item"
text = foreign_ "Text"
textInput = foreign_ "TextInput"
toolbarAndroid = foreign_ "ToolbarAndroid"
touchableHighlight = foreign_ "TouchableHighlight"
touchableNativeFeedback = foreign_ "TouchableNativeFeedback"
touchableOpacity = foreign_ "TouchableOpacity"
touchableWithoutFeedback = foreign_ "TouchableWithoutFeedback"
view = foreign_ "View"
viewPagerAndroid = foreign_ "ViewPagerAndroid"
webView = foreign_ "WebView"
